department-of-veterans-affairs/tmf-auth-exp-design-patterns

- .github/workflows/add-issue-to-second-project.yml
- .github/workflows/assign-user-from-label.yml
- .github/workflows/link-issue-as-dependency.yml
- .github/workflows/set-issue-label.yml
- .github/workflows/sync-status-across-projects.yml
- .github/workflows/update-issue-status.yml
Added GitHub action workflows to test in our repo
> Added github action workflows to test

- .github/workflows/update-issue-status.yml
> Added in PR number if issue number is not present

- .github/workflows/update-issue-status.yml
> #199 Deleting PR number, only sticking with issue number

- .github/workflows/assign-user-from-label.yml
- .github/workflows/update-issue-status.yml
> [#199] Fixing logic in update-issue-status

- .github/workflows/update-issue-status.yml
> [#199] Adding step to move issue to done in project

- .github/workflows/update-issue-status.yml
> [#199] Resolving issue with update-issue-status

- .github/workflows/update-issue-status.yml
> [#199] Get project and column id in update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199] Fixed the API URL to get project cards in update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199] Updated project name in update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199] Changed project name

- .github/workflows/update-issue-status.yml
> [#199] Fixed typo, token

- .github/workflows/update-issue-status.yml
> [#199] Changed api url for github projects

- .github/workflows/update-issue-status.yml
> [#199] Updated api request to use new github projects beta api

- .github/workflows/update-issue-status.yml
> [#199] Fixing indentation for yaml

- .github/workflows/update-issue-status.yml
> [#199] Updated update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199] Debugging response in update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199[ Fixing the curl command in update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199] Fixed the query string in the curl command

- .github/workflows/update-issue-status.yml
> [#199] Remove extra space after query slash

- .github/workflows/update-issue-status.yml
> [#199] Turned graphql query to one line

- .github/workflows/update-issue-status.yml
> [#199] Changed token

- .github/workflows/update-issue-status.yml
> [#199] Added project number

- .github/workflows/update-issue-status.yml
> [#199] Changed graphql to one line in step 4 of update-issue-status.yml

- .github/workflows/update-issue-status.yml
> [#199] Fixing value in mutation query

- .github/workflows/update-issue-status.yml
> [#199] Changed to singleSelectOptionId
